### ISSUE TITLE
iSH Shell

### ISSUE THREAD

**Issue by gijdeme** [Xaliks/Image-Parser#1]
Привет. А как запускать на iPhone? У меня iSH Shell

**Comment by Xaliks** [comment]
1. Установи туда git и node js
2. Напиши в консоль **git clone https://github.com/Xaliks/Image-Parser/**
3. (Опять в консоль) **npm i**
4. Запусти парсер командой **node parser.js** или **node .**

**Comment by Xaliks** [comment]
Извиняюсь за долгий ответ. Только сейчас вспомнил про этот парсер 😅
